config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
      resources :comments
  end
  root 'messages#index'
end

app/models/comment.rb
#
# Comment class
#
class Comment < ActiveRecord::Base

  # A comment is attached to a message on the message board.
  belongs_to :message

  # A comment was posted by a specific user.
  belongs_to :user

  # A comment must contain text content between the size of 1 and 500.
  validates :content, :presence => true, :uniqueness => false,
    :length => { :within => 1..500 }
end

app/models/message.rb
#
# Message class
#
class Message < ActiveRecord::Base

    # A message belongs to a single user.
    belongs_to :user

    # A message contains 0+ comments
    has_many :comments

    # A message must have title of length > 0 and up to 100.
    validates :title, :presence => true, :uniqueness => true,
      :length => { :within => 1..100 }

    # A message must have a body of length > 0 and up to 5000.
    validates :description, :presence => true, :uniqueness => false,
      :length => { :within => 1..5000 }
end

app/models/user.rb
#
# User class
#
class User < ActiveRecord::Base

  # Users can create 1 or more messages.
  has_many :messages

  # Users can post 1 or more comments to messages.
  has_many :comments

  # A user must have first name of length > 0 and up to 100.
  validates :first_name, :presence => true, :uniqueness => false, :length => { :within => 1..100 }

  # A user must have last name of length > 0 and up to 100.
  validates :last_name, :presence => true, :uniqueness => false, :length => { :within => 1..100 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    #
    # Define which parameter are permitted by the application.
    #
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
          :last_name, :description, :about_me])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_message
    before_action :find_comment, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    def create
        @comment = @message.comments.create(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
           redirect_to message_path(@message)
        else
           render 'new'
        end
    end

    def edit
    end

    def update
        if @comment.update(comment_params)
            redirect_to message_path(@message)
        else
            render 'edit'
        end
    end

    def destroy
        @comment.destroy
        redirect_to message_path(@message)
    end

    private

    def comment_params
        params.require(:comment).permit(:content)
    end

    def find_message
        @message = Message.find(params[:message_id])
    end

    def find_comment
        @comment = @message.comments.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    before_action :find_message, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def index
       @messages = Message.all.order("created_at DESC")
    end

    def show
    end

    def new
        @message = current_user.messages.build
    end

    def create
        @message = current_user.messages.build(message_params)
        if @message.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
       if @message.update(message_params)
            redirect_to message_path
       else
            render 'edit'
       end
    end

    def destroy
        @message.destroy
        redirect_to root_path
    end
   
    # Private defines. 
    private

    def message_params
        params.require(:message).permit(:title, :description)
    end

    def find_message
        @message = Message.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
    <p class="comment-content"><%= comment.content %></p>
    <p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago.</p>

    <div class="links">
    <% if user_signed_in? %>
        <% if comment.user_id == current_user.id %>
            <%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
            <%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: {confirm: "Delete this comment?" } %>
        <% end %>
    <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment for the following post:</h1>
<h3>"<%= @message.title %>"</h3>
<br>
<h4>Please type your comment below...</h4>
<br>
<%= simple_form_for([@message, @comment]) do |f| %>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyMsgboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-brand">
            <%= link_to "Simple Message Board", root_path, class: "navbar-brand navbar-link" %>
            </div>
            <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                    <li><%= link_to "Sign Out", destroy_user_session_path, class: "navbar-text", method: :delete %></li>
                <% else %>
                    <li><%= link_to "Sign Up", new_user_registration_path, class: "navbar-text" %></li>
                    <li><%= link_to "Login", new_user_session_path, class: "navbar-text" %></li>
                <% end %>
            </ul>
            <div><%= link_to "New Message", new_message_path, class: "navbar-brand navbar-right navbar-text" %></div>
        </div>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
        <%= yield %>
    </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
    <%= f.input :title, label: "Message Title" %>
    <%= f.input :description %>
    <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% if @messages.length > 0 %>
    <% @messages.each do |message| %>
        <div class="col-md-4">
            <div class="message">
                <h2 class="message-title"><%= message.title %></h2>
                <%= link_to "View Message", message_path(message), class: "btn btn-default" %>
            </div>
        </div>
    <% end %>
<% else %>
  <div name="no_messages_are_currently_present_text" class="col-md-12">
      Click the "New Message" button in the upper-right corner to add a new post to the message board.
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
    <h1>New Message</h1>

    <%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="message-show">
        <h2><%= @message.title %></h2>

        <p class="message-posted-by">Posted by
            <%= @message.user.email %>
            <%= time_ago_in_words(@message.created_at) %>
            ago.
        </p>

        <p class="message-description"><%= @message.description %></p>

        <div class="links btn-group">
            <%= link_to "Back to Message Board", root_path, class: "btn btn-default" %>

            <% if user_signed_in? %> 
                <% if @message.user_id == current_user.id %>
                    <%= link_to "Edit Post Content", edit_message_path(@message), class: "btn btn-default" %>
                    <%= link_to "Delete Post", message_path(@message), class: "btn btn-default",
                       method: :delete, data: {confirm: "Are you sure you want to delete this?"} %>
                <% end %>
            <% end %>
        </div>

        <br>

        <h3>Comments</h3>
        <%= render @message.comments %>

        <h3 class="reply-to-msg">Reply to Message:</h3>
        <%= render 'comments/form' %>
    </div>
</div>